language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4.8
  - DJANGO=1.5.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q nose --use-mirrors
  - pip install -q django-nose --use-mirrors
  - pip install -e . --use-mirrors
script:
  - python setup.py test
